//
// Autogenerated by Thrift Compiler (0.9.3)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;


var ttypes = require('./Server_types');
//HELPER FUNCTIONS AND STRUCTURES

Server_receiveMsg_args = function(args) {
  this.packet = null;
  this.id = null;
  if (args) {
    if (args.packet !== undefined && args.packet !== null) {
      this.packet = new ttypes.Packet(args.packet);
    }
    if (args.id !== undefined && args.id !== null) {
      this.id = args.id;
    }
  }
};
Server_receiveMsg_args.prototype = {};
Server_receiveMsg_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.packet = new ttypes.Packet();
        this.packet.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.id = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Server_receiveMsg_args.prototype.write = function(output) {
  output.writeStructBegin('Server_receiveMsg_args');
  if (this.packet !== null && this.packet !== undefined) {
    output.writeFieldBegin('packet', Thrift.Type.STRUCT, 1);
    this.packet.write(output);
    output.writeFieldEnd();
  }
  if (this.id !== null && this.id !== undefined) {
    output.writeFieldBegin('id', Thrift.Type.STRING, 2);
    output.writeString(this.id);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

Server_receiveMsg_result = function(args) {
};
Server_receiveMsg_result.prototype = {};
Server_receiveMsg_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Server_receiveMsg_result.prototype.write = function(output) {
  output.writeStructBegin('Server_receiveMsg_result');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

ServerClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
};
ServerClient.prototype = {};
ServerClient.prototype.seqid = function() { return this._seqid; }
ServerClient.prototype.new_seqid = function() { return this._seqid += 1; }
ServerClient.prototype.receiveMsg = function(packet, id, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_receiveMsg(packet, id);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_receiveMsg(packet, id);
  }
};

ServerClient.prototype.send_receiveMsg = function(packet, id) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('receiveMsg', Thrift.MessageType.CALL, this.seqid());
  var args = new Server_receiveMsg_args();
  args.packet = packet;
  args.id = id;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

ServerClient.prototype.recv_receiveMsg = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new Server_receiveMsg_result();
  result.read(input);
  input.readMessageEnd();

  callback(null)
};
ServerProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
ServerProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

ServerProcessor.prototype.process_receiveMsg = function(seqid, input, output) {
  var args = new Server_receiveMsg_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.receiveMsg.length === 2) {
    Q.fcall(this._handler.receiveMsg, args.packet, args.id)
      .then(function(result) {
        var result = new Server_receiveMsg_result({success: result});
        output.writeMessageBegin("receiveMsg", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("receiveMsg", Thrift.MessageType.EXCEPTION, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.receiveMsg(args.packet, args.id, function (err, result) {
      if (err == null) {
        var result = new Server_receiveMsg_result((err != null ? err : {success: result}));
        output.writeMessageBegin("receiveMsg", Thrift.MessageType.REPLY, seqid);
      } else {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("receiveMsg", Thrift.MessageType.EXCEPTION, seqid);
      }
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

